import {RFValue} from 'react-native-responsive-fontsize';
import {colors} from './colors';
import {fontTypes} from '../../utils/enums';
import {CustomTheme} from '../interfaces/theme/customTheme';
import {DefaultTheme} from '@react-navigation/native';

const SCREEN_HEIGHT_REFERENCE = 742;

/**
 * This can be used to create different themes
 * like dark and light. It can be then connected to
 * React context and controlled via a setting flag.
 */

const lightTheme: CustomTheme = {
  ...DefaultTheme,
  primary: colors.primary,
  secondary: colors.secondary,
  info: colors.info,
  homeBackground: '#FFFFFF',
  fonts: {
    regular: fontTypes.regular,
    semi_bold: fontTypes.semi_bold,
    bold: fontTypes.bold,
  },
  text: {
    textPrimary: colors.primary,
    dark: '#5B5B5B',
    light: '#FFFFFF',
    placeholder: '#B2AEAE',
    border: '#979797',
    borderFocus: '#80CBC4',
    lightGreen: '#1C6758',
    grey: '#979797',
    black: '#000000',
    s1: RFValue(44, SCREEN_HEIGHT_REFERENCE),
    s2: RFValue(32, SCREEN_HEIGHT_REFERENCE),
    s3: RFValue(28, SCREEN_HEIGHT_REFERENCE),
    s4: RFValue(25, SCREEN_HEIGHT_REFERENCE),
    s5: RFValue(23, SCREEN_HEIGHT_REFERENCE),
    s6: RFValue(20, SCREEN_HEIGHT_REFERENCE),
    s7: RFValue(17, SCREEN_HEIGHT_REFERENCE),
    s8: RFValue(16, SCREEN_HEIGHT_REFERENCE),
    s85: RFValue(15.5, SCREEN_HEIGHT_REFERENCE),
    s89: RFValue(14.2, SCREEN_HEIGHT_REFERENCE),
    s9: RFValue(14, SCREEN_HEIGHT_REFERENCE),
    s10: RFValue(12, SCREEN_HEIGHT_REFERENCE),
    s11: RFValue(10, SCREEN_HEIGHT_REFERENCE),
    s12: RFValue(8, SCREEN_HEIGHT_REFERENCE),
  },
  icon: {
    background: '#FFFFFF',
    icon: colors.primary,
    label: '#000000',
  },
  header: {
    background: '#C500FF',
    title: '#000000',
  },
  textInput: {
    activeUnderlineColor: colors.secondary,
    underlineColor: colors.primary,
    eyeIcon: '#aaaaaa',
    required: '#D80027',
  },
  searchBar: {
    border: '#979797',
    icon: '#979797',
    background: '#FFFFFF',
    placeHolder: '#B2AEAE',
    value: '#000000',
  },
  tabs: {
    activeItem: 'red',
    inActiveItem: '#000000',
    background: '#F2F2F2',
  },
  modal: {
    containerBackground: '#1C2340ab',
    titleBackground: colors.primary,
    title: '#FFFFFF',
    messageBackground: '#FFFFFF',
    message: '#000000',
    okTitle: '#FFFFFF',
    okBackground: colors.primary,
    borderColor: '#E4E4F1',
  },
  product: {
    background: '#F5F5F5',
    name: '#000000',
    size: '#000000',
    price: '#979797',
    offerPrice: colors.primary,
    rating: '#B80FEA',
    shadowStart: '#44444440',
    shadowEnd: '#eeeeeedd',
    ripple: '#44444440',
  },
  category: {
    background: 'transparent',
    name: '#000000',
    shadowStart: '#44444440',
    shadowEnd: '#eeeeeedd',
    ripple: '#44444440',
  },
  rating: {
    star: colors.primary,
  },
  favorite: {
    favoriteHeart: '#FFFFFF',
    unFavoriteHeart: '#000000',
    favoriteBackground: colors.secondary,
    unFavoriteBackground: '#FFFFFF',
    shadowStart: '#44444440',
    shadowEnd: '#eeeeeedd',
    emptyTitle: '#000000',
    emptyMessage: '#888888',
  },
  cartIcon: {
    addedCart: '#FFFFFF',
    unAddedCart: '#000000',
    addedBackground: colors.secondary,
    unAddedBackground: '#FFFFFF',
    shadowStart: '#44444440',
    shadowEnd: '#eeeeeedd',
  },
  animationPaginationDots: {
    selectedDot: colors.primary,
    unSelectedDot: '#D2D2D2',
  },
  button: {
    title: '#FFFFFF',
  },
  cartItem: {
    containerBackground: '#FFFFFF',
    containerBorder: '#E6E6E6',
    title: '#000000',
    price: colors.primary,
    close: '#000000',
    minus: '#000000',
    plus: colors.primary,
    quantityBorder: '#000000',
    quantity: '#000000',
    minusBackground: '#D2D2D2',
    shadowStart: '#00000016',
    shadowEnd: '#ffffff',
  },
  favoriteItem: {
    containerBackground: '#FFFFFF',
    containerBorder: '#E6E6E6',
    title: '#000000',
    price: colors.primary,
    shadowStart: '#00000016',
    shadowEnd: '#ffffff',
  },
  orderListItem: {
    containerBackground: '#FFFFFF',
    containerBorder: '#E6E6E6',
    cancelIconBackground: '#D80027',
    checkIconBackground: '#1DBF73',
    shippedIconBackground: colors.secondary,
    icon: '#FFFFFF',
    date: '#5B5B5B',
    text: '#000000',
    price: colors.primary,
  },
  comment: {
    imageBorder: '#979797',
    title: '#282728',
    text: '#000000',
  },
  signIn: {
    title: '#000000',
    submitBackground: colors.secondary,
    forgot: '#979797',
    appName: colors.primary,
    guest: '#979797',
  },
  home: {
    title: '#000000',
  },
  productDetails: {
    title: '#1C6758',
    description: '#5B5B5B',
    shareIcon: colors.secondary,
    shareIconBackground: '#FFFFFF',
    shadowStart: '#44444440',
    shadowEnd: '#eeeeeedd',
    offerPrice: colors.primary,
    price: '#979797',
    addButtonBackground: colors.secondary,
    buyButtonBackground: colors.primary,
  },
  productReview: {
    containerBorder: '#E6E6E6',
    separator: '#D2D2D2',
    lightText: '#949090',
    darkText: '#282728',
    emptyStar: '#000000',
  },
  writeReview: {
    text: '#000000',
    placeHolderComment: '#777474',
    grayText: '#666363',
    submitBackground: colors.primary,
    containerBorder: '#E6E6E6',
    emptyStar: '#000000',
  },
  placeOrder: {
    containerBorder: '#E6E6E6',
    lightText: '#5B5B5B',
    darkText: '#000000',
    coloredText: colors.primary,
    grayContainerBackground: '#D9D9D9',
    submitBackground: colors.primary,
    separator: '#D2D2D2',
    outlineCircle: '#000000',
    solidCircle: colors.primary,
  },
  cart: {
    border: '#E6E6E6',
    totalPrice: '#000000',
    shoppingBackground: colors.secondary,
    checkOutBackground: colors.primary,
    emptyTitle: '#000000',
    emptyMessage: '#888888',
  },
  profile: {
    title: colors.primary,
    subTitle: '#A7A3A7',
    containerBorder: '#E6E6E6',
    textInputBorder: '#000000',
    imageBorder: '#FFFFFF',
    category: '#000000',
    label: '#9B9B9B',
    text: '#000000',
    icon: '#000000',
    editAccountBackground: colors.primary,
    logOutBackground: '#D80027',
  },
  privacyPolicy: {
    text: '#000000',
  },
};

export default lightTheme;
